version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    #command: /bin/sh -c "while sleep 1000; do :; done"
